/**
 * User-visible acceptance for rules, hold correction, body phase, objectives,
 * and contact-triggered replanning. All judgments use disclosed fixture data;
 * the public video is never represented as model-generated beta or ground truth.
 */
import { expect, test } from '@playwright/test';

test('turns a public climbing clip into an honest, correctable coaching lab', async ({ page }) => {
  await page.goto('/?sample=holds');

  await expect(page.getByTestId('climbing-intelligence-lab')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Your climbing map' })).toBeVisible();
  await expect(page.getByTestId('classic-style-lab')).toContainText('岩策');
  await expect(page.getByTestId('video-truth')).toContainText('not generated by YanCe');
  await expect(page.getByTestId('video-truth')).toContainText('fixture data');

  // The numbers now have one clear meaning: ordered holds on the proposed path.
  const routePath = page.getByTestId('route-path-legend');
  await expect(routePath).toContainText('1 · Start · Jug proposal');
  await expect(routePath).toContainText('2 · Next · Edge proposal');
  await expect(routePath).toContainText('3 · Top · Sloper proposal');
  await expect(page.getByTestId('marker-key')).toContainText('X = off-route example');
  await expect(page.getByTestId('marker-key')).toContainText('V = optional volume');
  await expect(page.getByTestId('hold-marker-jug-4')).toContainText('Jug');
  await expect(page.getByTestId('hold-marker-edge-7')).toContainText('Edge');
  await expect(page.getByTestId('hold-marker-sloper-9')).toContainText('Sloper');
  await expect(page.getByTestId('active-hold-label')).toContainText(
    'Fixture proposal · not a model score',
  );

  // Hold-shape proposal can be corrected by a person and its provenance changes.
  await page.getByTestId('hold-marker-off-color').click();
  await expect(page.getByTestId('active-hold-label')).toContainText('Unknown');
  await page.getByTestId('label-jug').click();
  await expect(page.getByTestId('active-hold-label')).toContainText('Jug');
  await expect(page.getByTestId('active-hold-label')).toContainText('Human confirmed');

  // Tape/list membership is configured; pixels do not decide a universal rule.
  await expect(page.getByTestId('route-decision')).toContainText('Needs confirmation');
  await page.getByTestId('policy-explicit_hold_ids').click();
  await expect(page.getByTestId('route-decision')).toContainText('Allowed');

  // One wall produces three different answers when the user's goal changes.
  await expect(page.getByTestId('top-move-name')).toContainText('Quiet jug reset');
  await page.getByTestId('objective-technique_practice').click();
  await expect(page.getByTestId('top-move-name')).toContainText('Flag-and-edge practice');
  await page.getByTestId('objective-power_training').click();
  await expect(page.getByTestId('top-move-name')).toContainText('High sloper drive');

  // Crouching is explained in the context of a movement phase.
  await page.getByTestId('phase-loading').click();
  await expect(page.getByTestId('phase-explanation')).toContainText('not automatically inefficient');

  // Confirmed contact invalidates the old plan and produces an auditable update.
  await page.getByTestId('confirm-contact').click();
  await expect(page.getByTestId('live-update')).toContainText('Plan updated');
  await expect(page.getByTestId('live-update')).toContainText('confirmed left-foot contact');

  await expect(page.getByRole('link', { name: 'Read the complete research and build report' })).toHaveAttribute(
    'href',
    '/YANCE-CLIMBING-INTELLIGENCE-0720.html',
  );
});
